modules:
  - ./bridge-http
  - ./bridge-install
  - ./bridge-ipc
  - ./bridge-probe
  - ./core
  - ./harmon-collector
  - ./history-sqlite
  - ./plugins/sqldelight-gen
  - ./selftest

plugins:
  - ./plugins/sqldelight-gen
