modules:
  - ./bridge-http
  - ./bridge-install
  - ./bridge-ipc
  - ./bridge-probe
  - ./core
  - ./harmon-collector
  - ./history-sqlite
  - ./plugins/sqldelight-gen
  - ./selftest
  - ./webuicheck
  - ./webuitest

plugins:
  - ./plugins/sqldelight-gen
